# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/motorola/msm8937-common/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter ahannah cedric hannah james montana rhannah aljeter,$(TARGET_DEVICE)),)

endif
